export const CREATE_SEEKER = 'CREATE_SEEKER';
export const UPDATE_SEEKER = 'UPDATE_SEEKER';
export const COMPLETE_SEEKER_PROFILE = 'COMPLETE_SEEKER_PROFILE';
export const USER_START_CALL = 'USER_START_CALL';
export const ON_ERROR = 'ON_ERROR';
export const GET_SEEKER = 'GET_SEEKER';
export const USER_PROFILE_CLEAR = 'USER_PROFILE_CLEAR';