// NOTIFICATIONS
export const NOTIFICATIONS_CATCH_ERROR = 'NOTIFICATIONS_CATCH_ERROR';
export const NOTIFICATIONS_START_CALL = 'NOTIFICATIONS_START_CALL';
export const NOTIFICATIONS_END_CALL = 'NOTIFICATIONS_END_CALL';
export const NOTIFICATIONS_NOTIFICATIONS_FETCHED =
  'NOTIFICATIONS_NOTIFICATIONS_FETCHED';
