export const USER_CONNECTION_LIST_FETCHED = 'USER_CONNECTION_LIST_FETCHED';
export const USER_CONNECTION_LIST_FETCHED_ERROR = 'USER_CONNECTION_LIST_FETCHED_ERROR'
export const USER_CONVERSATION_LIST_FETCHED = 'USER_CONVERSATION_LIST_FETCHED';
export const MESSAGING_CLEAR = 'MESSAGING_CLEAR';