// OPPORTUNITY
export const OPPORTUNITY_CATCH_ERROR = 'OPPORTUNITY_CATCH_ERROR';
export const OPPORTUNITY_START_CALL = 'OPPORTUNITY_START_CALL';
export const OPPORTUNITY_END_CALL = 'OPPORTUNITY_END_CALL';
export const OPPORTUNITY_OPPORTUNITIES_FETCHED =
  'OPPORTUNITY_OPPORTUNITIES_FETCHED';
export const OPPORTUNITY_FETCHED = 'OPPORTUNITY_FETCHED';
export const OPPORTUNITY_ATTEENDE_CREATED = 'OPPORTUNITY_ATTEENDE_CREATED';
export const OPPORTUNITY_ATTENDEE_UPDATED = 'OPPORTUNITY_ATTENDEE_UPDATED';
export const OPPORTUNITY_CLEAR = 'OPPORTUNITY_CLEAR';
