// providers
export const PROVIDERS_CATCH_ERROR = 'PROVIDERS_CATCH_ERROR';
export const PROVIDERS_START_CALL = 'PROVIDERS_START_CALL';
export const PROVIDERS_END_CALL = 'PROVIDERS_END_CALL';
export const PROVIDERS_FETCHED = 'PROVIDERS_FETCHED';
export const PROVIDER_FETCHED = 'PROVIDER_FETCHED';
export const PROVIDER_FOLLOWER_CREATED = 'PROVIDER_FOLLOWER_CREATED';
export const PROVIDER_FOLLOWER_UPDATED = 'PROVIDER_FOLLOWER_UPDATED';
export const PROVIDERS_CLEAR = 'PROVIDERS_CLEAR';
