// PROFILE
export const PROFILE_CATCH_ERROR = 'PROFILE_CATCH_ERROR';
export const PROFILE_START_CALL = 'PROFILE_START_CALL';
export const PROFILE_END_CALL = 'PROFILE_END_CALL';
export const PROFILE_MY_COLLABORATIONS_FETCHED =
  'PROFILE_MY_COLLABORATIONS_FETCHED';
export const PROFILE_MY_OPPORTUNITIES_FETCHED =
  'PROFILE_MY_OPPORTUNITIES_FETCHED';
export const PROFILE_CONNECTION_PROVIDERS_FETCHED =
  'PROFILE_CONNECTION_PROVIDERS_FETCHED';
export const PROFILE_CONNECTION_SEEKERS_FETCHED =
  'PROFILE_CONNECTION_SEEKERS_FETCHED';
export const PROFILE_FRIENDSHIP_REQUESTERS_FETCHED =
  'PROFILE_FRIENDSHIP_REQUESTERS_FETCHED';
export const PROFILE_FRIENDSHIP_UPDATED = 'PROFILE_FRIENDSHIP_UPDATED';
export const PROFILE_FRIENDSHIP_REQUESTER_UPDATED =
  'PROFILE_FRIENDSHIP_REQUESTER_UPDATED';
export const PROFILE_FRIENDSHIP_CREATED = 'PROFILE_FRIENDSHIP_CREATED';
export const PROFILE_FRIENDSHIP_REQUEST_CREATED =
  'PROFILE_FRIENDSHIP_REQUEST_CREATED';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';

//Get seeker (Edit Profile)
export const GET_SEEKER_PROFILE = 'GET_SEEKER_PROFILE';

//Get Posts via getRouteMap
export const PROFILE_POSTS_FETCHED = 'PROFILE_POSTS_FETCHED';
export const PROFILE_CLEAR = 'PROFILE_CLEAR';
