// DISCOVER
export const DISCOVER_CATCH_ERROR = 'DISCOVER_CATCH_ERROR';
export const DISCOVER_START_CALL = 'DISCOVER_START_CALL';
export const DISCOVER_END_CALL = 'DISCOVER_END_CALL';
export const DISCOVER_INSERT_RECENT_SEARCHES = 'DISCOVER_INSERT_RECENT_SEARCHES';
export const DISCOVER_LIST_RECENT_SEARCHES = 'DISCOVER_LIST_RECENT_SEARCHES';
export const DISCOVER_SEARCH_START_CALL = 'DISCOVER_SEARCH_START_CALL';
export const DISCOVER_PROVIDERS_SEARCHED = 'DISCOVER_PROVIDERS_SEARCHED';
export const DISCOVER_OPPORTUNITIES_SEARCHED = 'DISCOVER_OPPORTUNITIES_SEARCHED';
export const DISCOVER_SEEKERS_SEARCHED = 'DISCOVER_SEEKERS_SEARCHED';
export const DISCOVER_COLLABORATIONS_SEARCHED = 'DISCOVER_COLLABORATIONS_SEARCHED';
export const DISCOVER_SEARCH_RESULT = 'DISCOVER_SEARCH_RESULT';
export const DISCOVER_CONTENTS_FETCHED = 'DISCOVER_CONTENTS_FETCHED';
export const DISCOVER_OPPORTUNITIES_FETCHED = 'DISCOVER_OPPORTUNITIES_FETCHED';
export const DISCOVER_COLLABORATIONS_FETCHED = 'DISCOVER_COLLABORATIONS_FETCHED';
export const DISCOVER_CONNECTIONS_POSTS_FETCHED = 'DISCOVER_CONNECTIONS_POSTS_FETCHED';
export const DISCOVER_FETCHED = 'DISCOVER_FETCHED';
export const DISCOVER_CLEAR = 'DISCOVER_CLEAR';
