// COLLABORATION
export const COLLABORATION_CATCH_ERROR = 'COLLABORATION_CATCH_ERROR';
export const COLLABORATION_START_CALL = 'COLLABORATION_START_CALL';
export const OCOLLABORATION_END_CALL = 'OCOLLABORATION_END_CALL';
export const COLLABORATION_COLLABORATIONS_FETCHED = 'COLLABORATION_COLLABORATIONS_FETCHED';
export const COLLABORATION_FETCHED = 'COLLABORATION_FETCHED';
export const COLLABORATION_CREATED = 'COLLABORATION_CREATED';
export const COLLABORATION_UPDATED = 'COLLABORATION_UPDATED';
export const COLLABORATION_MEMBER_CREATED = 'COLLABORATION_MEMBER_CREATED';
export const COLLABORATION_MEMBER_UPDATED = 'COLLABORATION_MEMBER_UPDATED';
export const COLLABORATION_CLEAR = 'COLLABORATION_CLEAR';
