// route maps
export const ROUTEMAPS_CATCH_ERROR = 'ROUTEMAPS_CATCH_ERROR';
export const ROUTEMAPS_START_CALL = 'ROUTEMAPS_START_CALL';
export const ROUTEMAPS_END_CALL = 'ROUTEMAPS_END_CALL';
export const ROUTEMAPS_FETCHED = 'ROUTEMAPS_FETCHED';
export const ROUTEMAPS_CREATED = 'ROUTEMAPS_CREATED';
export const ROUTEMAPS_UPDATE_FORM = 'ROUTEMAPS_UPDATE_FORM';
export const ROUTEMAPS_UPDATE_VALUE = 'ROUTEMAPS_UPDATE_VALUE';
export const ROUTEMAPS_RESET_FORM = 'ROUTEMAPS_RESET_FORM';
export const ROUTEMAP_FETCHED = 'ROUTEMAP_FETCHED';
export const ROUTEMAP_UPDATED = 'ROUTEMAP_UPDATED';
export const ROUTEMAPS_CATEGORIES_FETCHED = 'ROUTEMAPS_CATEGORIES_FETCHED';
export const ROUTEMAPS_CLEAR = 'ROUTEMAPS_CLEAR';
