// seekers
export const SEEKERS_CATCH_ERROR = 'SEEKERS_CATCH_ERROR';
export const SEEKERS_START_CALL = 'SEEKERS_START_CALL';
export const SEEKERS_END_CALL = 'SEEKERS_END_CALL';
export const SEEKERS_SEEKER_FETCHED = 'SEEKERS_SEEKER_FETCHED';
export const SEEKERS_FRIENDSHIP_UPDATED = 'SEEKERS_FRIENDSHIP_UPDATED';
export const SEEKERS_FRIENDSHIP_REQUESTER_UPDATED = 'SEEKERS_FRIENDSHIP_REQUESTER_UPDATED';
export const SEEKERS_FRIENDSHIP_CREATED = 'SEEKERS_FRIENDSHIP_CREATED';
export const SEEKERS_FRIENDSHIP_REQUEST_CREATED = 'SEEKERS_FRIENDSHIP_REQUEST_CREATED';
export const SEEKERS_ROUTEMAP_FETCHED = 'SEEKERS_ROUTEMAP_FETCHED';
export const SEEKERS_CLEAR = 'SEEKERS_CLEAR';
